### PR TITLE
MST++

### PR DESCRIPTION
**Pull request by leilaMozaffari8**
MST++ test set implementation

### CODE REVIEW

**Review by harukadoyu — CHANGES_REQUESTED** [review]
The notebook is already quite clear. I just want you give a slightly more explanation in some points (like background of this dataset/competition), and remove unnecessary code (you have defined `load_and_visualize_mat_v7_3()` twice, one is enough, `if __name__ == "__main__":` is probably unneeded). Thank you for researching!

Edit: Also, could you check if it's possible to load any model by `torch.load` and print its structure in the notebook

**Comment by harukadoyu** [comment]
Also, could you check if it's possible to load any model by `torch.load` and print its structure in the notebook

**Comment by leilaMozaffari8** [comment]
> Also, could you check if it's possible to load any model by `torch.load` and print its structure in the notebook

MST_Plus_Plus(
  (conv_in): Conv2d(3, 31, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
  (body): Sequential(
    (0): MST(
      (embedding): Conv2d(31, 31, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (encoder_layers): ModuleList(
        (0): ModuleList(
          (0): MSAB(
            (blocks): ModuleList(
              (0): ModuleList(
                (0): MS_MSA(
                  (to_q): Linear(in_features=31, out_features=31, bias=False)
                  (to_k): Linear(in_features=31, out_features=31, bias=False)
                  (to_v): Linear(in_features=31, out_features=31, bias=False)
                  (proj): Linear(in_features=31, out_features=31, bias=True)
                  (pos_emb): Sequential(
                    (0): Conv2d(31, 31, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), groups=31, bias=False)
                    (1): GELU()
                    (2): Conv2d(31, 31, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), groups=31, bias=False)
                  )
                )
                (1): PreNorm(
                  (fn): FeedForward(
                    (net): Sequential(
                      (0): Conv2d(31, 124, kernel_size=(1, 1), stride=(1, 1), bias=False)
                      (1): GELU()
                      (2): Conv2d(124, 124, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), groups=124, bias=False)
                      (3): GELU()
                      (4): Conv2d(124, 31, kernel_size=(1, 1), stride=(1, 1), bias=False)
                    )
                  )
                  (norm): LayerNorm((31,), eps=1e-05, elementwise_affine=True)
                )
              )
            )
          )
          (1): Conv2d(31, 62, kernel_size=(4, 4), stride=(2, 2), padding=(1, 1), bias=False)
        )
        (1): ModuleList(
          (0): MSAB(
            (blocks): ModuleList(
              (0): ModuleList(
                (0): MS_MSA(
                  (to_q): Linear(in_features=62, out_features=62, bias=False)
                  (to_k): Linear(in_features=62, out_features=62, bias=False)
                  (to_v): Linear(in_features=62, out_features=62, bias=False)
                  (proj): Linear(in_features=62, out_features=62, bias=True)
                  (pos_emb): Sequential(
                    (0): Conv2d(62, 62, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), groups=62, bias=False)
                    (1): GELU()
                    (2): Conv2d(62, 62, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), groups=62, bias=False)
                  )
                )
                (1): PreNorm(
                  (fn): FeedForward(
                    (net): Sequential(
                      (0): Conv2d(62, 248, kernel_size=(1, 1), stride=(1, 1), bias=False)
                      (1): GELU()
                      (2): Conv2d(248, 248, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), groups=248, bias=False)
                      (3): GELU()
                      (4): Conv2d(248, 62, kernel_size=(1, 1), stride=(1, 1), bias=False)
                    )
                  )
                  (norm): LayerNorm((62,), eps=1e-05, elementwise_affine=True)
                )
              )
            )
          )
          (1): Conv2d(62, 124, kernel_size=(4, 4), stride=(2, 2), padding=(1, 1), bias=False)
        )
      )
      (bottleneck): MSAB(
        (blocks): ModuleList(
          (0): ModuleList(
            (0): MS_MSA(
              (to_q): Linear(in_features=124, out_features=124, bias=False)
              (to_k): Linear(in_features=124, out_features=124, bias=False)
              (to_v): Linear(in_features=124, out_features=124, bias=False)
              (proj): Linear(in_features=124, out_features=124, bias=True)
              (pos_emb): Sequential(
                (0): Conv2d(124, 124, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), groups=124, bias=False)
                (1): GELU()
                (2): Conv2d(124, 124, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), groups=124, bias=False)
              )
            )
            (1): PreNorm(
              (fn): FeedForward(
                (net): Sequential(
                  (0): Conv2d(124, 496, kernel_size=(1, 1), stride=(1, 1), bias=False)
                  (1): GELU()
                  (2): Conv2d(496, 496, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), groups=496, bias=False)
                  (3): GELU()
                  (4): Conv2d(496, 124, kernel_size=(1, 1), stride=(1, 1), bias=False)
                )
              )
              (norm): LayerNorm((124,), eps=1e-05, elementwise_affine=True)
            )
          )
        )
      )
      (decoder_layers): ModuleList(
        (0): ModuleList(
          (0): ConvTranspose2d(124, 62, kernel_size=(2, 2), stride=(2, 2))
          (1): Conv2d(124, 62, kernel_size=(1, 1), stride=(1, 1), bias=False)
          (2): MSAB(
            (blocks): ModuleList(
              (0): ModuleList(
                (0): MS_MSA(
                  (to_q): Linear(in_features=62, out_features=62, bias=False)
                  (to_k): Linear(in_features=62, out_features=62, bias=False)
                  (to_v): Linear(in_features=62, out_features=62, bias=False)
                  (proj): Linear(in_features=62, out_features=62, bias=True)
                  (pos_emb): Sequential(
                    (0): Conv2d(62, 62, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), groups=62, bias=False)
                    (1): GELU()
                    (2): Conv2d(62, 62, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), groups=62, bias=False)
                  )
                )
                (1): PreNorm(
                  (fn): FeedForward(
                    (net): Sequential(
                      (0): Conv2d(62, 248, kernel_size=(1, 1), stride=(1, 1), bias=False)
                      (1): GELU()
                      (2): Conv2d(248, 248, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), groups=248, bias=False)
                      (3): GELU()
                      (4): Conv2d(248, 62, kernel_size=(1, 1), stride=(1, 1), bias=False)
                    )
                  )
                  (norm): LayerNorm((62,), eps=1e-05, elementwise_affine=True)
                )
              )
            )
          )
        )
        (1): ModuleList(
          (0): ConvTranspose2d(62, 31, kernel_size=(2, 2), stride=(2, 2))
          (1): Conv2d(62, 31, kernel_size=(1, 1), stride=(1, 1), bias=False)
          (2): MSAB(
            (blocks): ModuleList(
              (0): ModuleList(
                (0): MS_MSA(
                  (to_q): Linear(in_features=31, out_features=31, bias=False)
                  (to_k): Linear(in_features=31, out_features=31, bias=False)
                  (to_v): Linear(in_features=31, out_features=31, bias=False)
                  (proj): Linear(in_features=31, out_features=31, bias=True)
                  (pos_emb): Sequential(
                    (0): Conv2d(31, 31, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), groups=31, bias=False)
                    (1): GELU()
                    (2): Conv2d(31, 31, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), groups=31, bias=False)
                  )
                )
                (1): PreNorm(
                  (fn): FeedForward(
                    (net): Sequential(
                      (0): Conv2d(31, 124, kernel_size=(1, 1), stride=(1, 1), bias=False)
                      (1): GELU()
                      (2): Conv2d(124, 124, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), groups=124, bias=False)
                      (3): GELU()
                      (4): Conv2d(124, 31, kernel_size=(1, 1), stride=(1, 1), bias=False)
                    )
                  )
                  (norm): LayerNorm((31,), eps=1e-05, elementwise_affine=True)
                )
              )
            )
          )
        )
      )
      (mapping): Conv2d(31, 31, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (lrelu): LeakyReLU(negative_slope=0.1, inplace=True)
    )
    (1): MST(
      (embedding): Conv2d(31, 31, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (encoder_layers): ModuleList(
        (0): ModuleList(
          (0): MSAB(
            (blocks): ModuleList(
              (0): ModuleList(
                (0): MS_MSA(
                  (to_q): Linear(in_features=31, out_features=31, bias=False)
                  (to_k): Linear(in_features=31, out_features=31, bias=False)
                  (to_v): Linear(in_features=31, out_features=31, bias=False)
                  (proj): Linear(in_features=31, out_features=31, bias=True)
                  (pos_emb): Sequential(
                    (0): Conv2d(31, 31, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), groups=31, bias=False)
                    (1): GELU()
                    (2): Conv2d(31, 31, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), groups=31, bias=False)
                  )
                )
                (1): PreNorm(
                  (fn): FeedForward(
                    (net): Sequential(
                      (0): Conv2d(31, 124, kernel_size=(1, 1), stride=(1, 1), bias=False)
                      (1): GELU()
                      (2): Conv2d(124, 124, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), groups=124, bias=False)
                      (3): GELU()
                      (4): Conv2d(124, 31, kernel_size=(1, 1), stride=(1, 1), bias=False)
                    )
                  )
                  (norm): LayerNorm((31,), eps=1e-05, elementwise_affine=True)
                )
              )
            )
          )
          (1): Conv2d(31, 62, kernel_size=(4, 4), stride=(2, 2), padding=(1, 1), bias=False)
        )
        (1): ModuleList(
          (0): MSAB(
            (blocks): ModuleList(
              (0): ModuleList(
                (0): MS_MSA(
                  (to_q): Linear(in_features=62, out_features=62, bias=False)
                  (to_k): Linear(in_features=62, out_features=62, bias=False)
                  (to_v): Linear(in_features=62, out_features=62, bias=False)
                  (proj): Linear(in_features=62, out_features=62, bias=True)
                  (pos_emb): Sequential(
                    (0): Conv2d(62, 62, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), groups=62, bias=False)
                    (1): GELU()
                    (2): Conv2d(62, 62, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), groups=62, bias=False)
                  )
                )
                (1): PreNorm(
                  (fn): FeedForward(
                    (net): Sequential(
                      (0): Conv2d(62, 248, kernel_size=(1, 1), stride=(1, 1), bias=False)
                      (1): GELU()
                      (2): Conv2d(248, 248, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), groups=248, bias=False)
                      (3): GELU()
                      (4): Conv2d(248, 62, kernel_size=(1, 1), stride=(1, 1), bias=False)
                    )
                  )
                  (norm): LayerNorm((62,), eps=1e-05, elementwise_affine=True)
                )
              )
            )
          )
          (1): Conv2d(62, 124, kernel_size=(4, 4), stride=(2, 2), padding=(1, 1), bias=False)
        )
      )
      (bottleneck): MSAB(
        (blocks): ModuleList(
          (0): ModuleList(
            (0): MS_MSA(
              (to_q): Linear(in_features=124, out_features=124, bias=False)
              (to_k): Linear(in_features=124, out_features=124, bias=False)
              (to_v): Linear(in_features=124, out_features=124, bias=False)
              (proj): Linear(in_features=124, out_features=124, bias=True)
              (pos_emb): Sequential(
                (0): Conv2d(124, 124, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), groups=124, bias=False)
                (1): GELU()
                (2): Conv2d(124, 124, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), groups=124, bias=False)
              )
            )
            (1): PreNorm(
              (fn): FeedForward(
                (net): Sequential(
                  (0): Conv2d(124, 496, kernel_size=(1, 1), stride=(1, 1), bias=False)
                  (1): GELU()
                  (2): Conv2d(496, 496, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), groups=496, bias=False)
                  (3): GELU()
                  (4): Conv2d(496, 124, kernel_size=(1, 1), stride=(1, 1), bias=False)
                )
              )
              (norm): LayerNorm((124,), eps=1e-05, elementwise_affine=True)
            )
          )
        )
      )
      (decoder_layers): ModuleList(
        (0): ModuleList(
          (0): ConvTranspose2d(124, 62, kernel_size=(2, 2), stride=(2, 2))
          (1): Conv2d(124, 62, kernel_size=(1, 1), stride=(1, 1), bias=False)
          (2): MSAB(
            (blocks): ModuleList(
              (0): ModuleList(
                (0): MS_MSA(
                  (to_q): Linear(in_features=62, out_features=62, bias=False)
                  (to_k): Linear(in_features=62, out_features=62, bias=False)
                  (to_v): Linear(in_features=62, out_features=62, bias=False)
                  (proj): Linear(in_features=62, out_features=62, bias=True)
                  (pos_emb): Sequential(
                    (0): Conv2d(62, 62, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), groups=62, bias=False)
                    (1): GELU()
                    (2): Conv2d(62, 62, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), groups=62, bias=False)
                  )
                )
                (1): PreNorm(
                  (fn): FeedForward(
                    (net): Sequential(
                      (0): Conv2d(62, 248, kernel_size=(1, 1), stride=(1, 1), bias=False)
                      (1): GELU()
                      (2): Conv2d(248, 248, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), groups=248, bias=False)
                      (3): GELU()
                      (4): Conv2d(248, 62, kernel_size=(1, 1), stride=(1, 1), bias=False)
                    )
                  )
                  (norm): LayerNorm((62,), eps=1e-05, elementwise_affine=True)
                )
              )
            )
          )
        )
        (1): ModuleList(
          (0): ConvTranspose2d(62, 31, kernel_size=(2, 2), stride=(2, 2))
          (1): Conv2d(62, 31, kernel_size=(1, 1), stride=(1, 1), bias=False)
          (2): MSAB(
            (blocks): ModuleList(
              (0): ModuleList(
                (0): MS_MSA(
                  (to_q): Linear(in_features=31, out_features=31, bias=False)
                  (to_k): Linear(in_features=31, out_features=31, bias=False)
                  (to_v): Linear(in_features=31, out_features=31, bias=False)
                  (proj): Linear(in_features=31, out_features=31, bias=True)
                  (pos_emb): Sequential(
                    (0): Conv2d(31, 31, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), groups=31, bias=False)
                    (1): GELU()
                    (2): Conv2d(31, 31, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), groups=31, bias=False)
                  )
                )
                (1): PreNorm(
                  (fn): FeedForward(
                    (net): Sequential(
                      (0): Conv2d(31, 124, kernel_size=(1, 1), stride=(1, 1), bias=False)
                      (1): GELU()
                      (2): Conv2d(124, 124, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), groups=124, bias=False)
                      (3): GELU()
                      (4): Conv2d(124, 31, kernel_size=(1, 1), stride=(1, 1), bias=False)
                    )
                  )
                  (norm): LayerNorm((31,), eps=1e-05, elementwise_affine=True)
                )
              )
            )
          )
        )
      )
      (mapping): Conv2d(31, 31, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (lrelu): LeakyReLU(negative_slope=0.1, inplace=True)
    )
    (2): MST(
      (embedding): Conv2d(31, 31, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (encoder_layers): ModuleList(
        (0): ModuleList(
          (0): MSAB(
            (blocks): ModuleList(
              (0): ModuleList(
                (0): MS_MSA(
                  (to_q): Linear(in_features=31, out_features=31, bias=False)
                  (to_k): Linear(in_features=31, out_features=31, bias=False)
                  (to_v): Linear(in_features=31, out_features=31, bias=False)
                  (proj): Linear(in_features=31, out_features=31, bias=True)
                  (pos_emb): Sequential(
                    (0): Conv2d(31, 31, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), groups=31, bias=False)
                    (1): GELU()
                    (2): Conv2d(31, 31, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), groups=31, bias=False)
                  )
                )
                (1): PreNorm(
                  (fn): FeedForward(
                    (net): Sequential(
                      (0): Conv2d(31, 124, kernel_size=(1, 1), stride=(1, 1), bias=False)
                      (1): GELU()
                      (2): Conv2d(124, 124, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), groups=124, bias=False)
                      (3): GELU()
                      (4): Conv2d(124, 31, kernel_size=(1, 1), stride=(1, 1), bias=False)
                    )
                  )
                  (norm): LayerNorm((31,), eps=1e-05, elementwise_affine=True)
                )
              )
            )
          )
          (1): Conv2d(31, 62, kernel_size=(4, 4), stride=(2, 2), padding=(1, 1), bias=False)
        )
        (1): ModuleList(
          (0): MSAB(
            (blocks): ModuleList(
              (0): ModuleList(
                (0): MS_MSA(
                  (to_q): Linear(in_features=62, out_features=62, bias=False)
                  (to_k): Linear(in_features=62, out_features=62, bias=False)
                  (to_v): Linear(in_features=62, out_features=62, bias=False)
                  (proj): Linear(in_features=62, out_features=62, bias=True)
                  (pos_emb): Sequential(
                    (0): Conv2d(62, 62, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), groups=62, bias=False)
                    (1): GELU()
                    (2): Conv2d(62, 62, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), groups=62, bias=False)
                  )
                )
                (1): PreNorm(
                  (fn): FeedForward(
                    (net): Sequential(
                      (0): Conv2d(62, 248, kernel_size=(1, 1), stride=(1, 1), bias=False)
                      (1): GELU()
                      (2): Conv2d(248, 248, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), groups=248, bias=False)
                      (3): GELU()
                      (4): Conv2d(248, 62, kernel_size=(1, 1), stride=(1, 1), bias=False)
                    )
                  )
                  (norm): LayerNorm((62,), eps=1e-05, elementwise_affine=True)
                )
              )
            )
          )
          (1): Conv2d(62, 124, kernel_size=(4, 4), stride=(2, 2), padding=(1, 1), bias=False)
        )
      )
      (bottleneck): MSAB(
        (blocks): ModuleList(
          (0): ModuleList(
            (0): MS_MSA(
              (to_q): Linear(in_features=124, out_features=124, bias=False)
              (to_k): Linear(in_features=124, out_features=124, bias=False)
              (to_v): Linear(in_features=124, out_features=124, bias=False)
              (proj): Linear(in_features=124, out_features=124, bias=True)
              (pos_emb): Sequential(
                (0): Conv2d(124, 124, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), groups=124, bias=False)
                (1): GELU()
                (2): Conv2d(124, 124, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), groups=124, bias=False)
              )
            )
            (1): PreNorm(
              (fn): FeedForward(
                (net): Sequential(
                  (0): Conv2d(124, 496, kernel_size=(1, 1), stride=(1, 1), bias=False)
                  (1): GELU()
                  (2): Conv2d(496, 496, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), groups=496, bias=False)
                  (3): GELU()
                  (4): Conv2d(496, 124, kernel_size=(1, 1), stride=(1, 1), bias=False)
                )
              )
              (norm): LayerNorm((124,), eps=1e-05, elementwise_affine=True)
            )
          )
        )
      )
      (decoder_layers): ModuleList(
        (0): ModuleList(
          (0): ConvTranspose2d(124, 62, kernel_size=(2, 2), stride=(2, 2))
          (1): Conv2d(124, 62, kernel_size=(1, 1), stride=(1, 1), bias=False)
          (2): MSAB(
            (blocks): ModuleList(
              (0): ModuleList(
                (0): MS_MSA(
                  (to_q): Linear(in_features=62, out_features=62, bias=False)
                  (to_k): Linear(in_features=62, out_features=62, bias=False)
                  (to_v): Linear(in_features=62, out_features=62, bias=False)
                  (proj): Linear(in_features=62, out_features=62, bias=True)
                  (pos_emb): Sequential(
                    (0): Conv2d(62, 62, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), groups=62, bias=False)
                    (1): GELU()
                    (2): Conv2d(62, 62, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), groups=62, bias=False)
                  )
                )
                (1): PreNorm(
                  (fn): FeedForward(
                    (net): Sequential(
                      (0): Conv2d(62, 248, kernel_size=(1, 1), stride=(1, 1), bias=False)
                      (1): GELU()
                      (2): Conv2d(248, 248, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), groups=248, bias=False)
                      (3): GELU()
                      (4): Conv2d(248, 62, kernel_size=(1, 1), stride=(1, 1), bias=False)
                    )
                  )
                  (norm): LayerNorm((62,), eps=1e-05, elementwise_affine=True)
                )
              )
            )
          )
        )
        (1): ModuleList(
          (0): ConvTranspose2d(62, 31, kernel_size=(2, 2), stride=(2, 2))
          (1): Conv2d(62, 31, kernel_size=(1, 1), stride=(1, 1), bias=False)
          (2): MSAB(
            (blocks): ModuleList(
              (0): ModuleList(
                (0): MS_MSA(
                  (to_q): Linear(in_features=31, out_features=31, bias=False)
                  (to_k): Linear(in_features=31, out_features=31, bias=False)
                  (to_v): Linear(in_features=31, out_features=31, bias=False)
                  (proj): Linear(in_features=31, out_features=31, bias=True)
                  (pos_emb): Sequential(
                    (0): Conv2d(31, 31, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), groups=31, bias=False)
                    (1): GELU()
                    (2): Conv2d(31, 31, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), groups=31, bias=False)
                  )
                )
                (1): PreNorm(
                  (fn): FeedForward(
                    (net): Sequential(
                      (0): Conv2d(31, 124, kernel_size=(1, 1), stride=(1, 1), bias=False)
                      (1): GELU()
                      (2): Conv2d(124, 124, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), groups=124, bias=False)
                      (3): GELU()
                      (4): Conv2d(124, 31, kernel_size=(1, 1), stride=(1, 1), bias=False)
                    )
                  )
                  (norm): LayerNorm((31,), eps=1e-05, elementwise_affine=True)
                )
              )
            )
          )
        )
      )
      (mapping): Conv2d(31, 31, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (lrelu): LeakyReLU(negative_slope=0.1, inplace=True)
    )
  )
  (conv_out): Conv2d(31, 31, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
)
Unsupported operator aten::rsub encountered 2 time(s)
Unsupported operator aten::reflection_pad2d encountered 1 time(s)
Unsupported operator aten::mul encountered 45 time(s)
Unsupported operator aten::norm encountered 30 time(s)
Unsupported operator aten::clamp_min encountered 30 time(s)
Unsupported operator aten::expand_as encountered 30 time(s)
Unsupported operator aten::div encountered 30 time(s)
Unsupported operator aten::softmax encountered 15 time(s)
Unsupported operator aten::add_ encountered 16 time(s)
Unsupported operator aten::gelu encountered 45 time(s)
Unsupported operator aten::add encountered 48 time(s)
The following submodules of the model were never called during the trace of the graph. They may be unused, or they were accessed by direct calls to .forward() or via other python methods. In the latter case they will have zeros for statistics, though their statistics will still contribute to their parent calling module.
body.0.lrelu, body.1.lrelu, body.2.lrelu
GMac:20.759536743164062
Params:1619625

**Comment by doyu** [comment]
@leilaMozaffari8 

please make sure not breaking the GH action.

image

**Pull request closed without merging**
